# Generated by Django 3.2.9 on 2021-12-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='identification',
            field=models.IntegerField(default=23944781),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
